from setuptools import setup, find_packages

setup(
    name="financial_ml_pipeline",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=0.24.0",
        "scipy>=1.7.0",
        "statsmodels>=0.13.0",
        "yfinance>=0.1.63",
        "ta>=0.7.0",
        "torch>=1.9.0",
        "torch-directml>=0.1.0",
        "optuna>=2.10.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "joblib>=1.0.0",
        "pyyaml>=5.4.0",
        "pytest>=6.2.0",
        "pytest-cov>=2.12.0",
        "black>=21.5b2",
        "pylint>=2.8.2",
        "mypy>=0.910",
        "pandas_datareader>=0.10.0",
        "TA-Lib>=0.4.24",
        "xgboost>=1.5.0",
        "lightgbm>=3.3.1",
        "markdown2>=2.4.0",
        "pdfkit>=0.6.1",
        "plotly>=5.0.0",
        "cvxopt>=1.2.7",
        "pathlib>=1.0.1",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive financial machine learning pipeline",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/financial_ml_pipeline",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.12",
)
